development:
  adapter: postgresql
  encoding: unicode
  database: discepto_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: discepto_test
  pool: 5
  username: root
  password:
  host: localhost
