development: &default
  adapter: postgresql
  database: discepto_development
  pool: 5
  timeout: 5000
  min_messages: warning

test: &test
  <<: *default
  database: discepto_test

cucumber:
  <<: *test
